# Generated by Django 5.1.4 on 2025-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="fhoto/blog_images", verbose_name="Изображение"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("publication", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("counter_views", models.IntegerField(verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["title"],
            },
        ),
    ]