# Generated by Django 5.1.4 on 2025-01-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="counter_views",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]