# Generated by Django 4.2.2 on 2025-09-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_publish_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="publish_product",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]